### ISSUE TITLE
No module named 'tornado'

### ISSUE THREAD

**Issue by aidiss** [farseerfc/pacvis#7]
Installed pacvis by `yay -S pacvis-git`

tried to run pacvis and received:

```
Traceback (most recent call last):
  File "/usr/local/bin/pacvis", line 11, in <module>
    load_entry_point('PacVis==0.2.7', 'console_scripts', 'pacvis')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/pacvis/pacvis.py", line 9, in <module>
    import tornado.ioloop
ModuleNotFoundError: No module named 'tornado'
```

**Comment by aidiss** [comment]
Fixed by `python37 -m pip install tornado`
